### PR TITLE
Various fixes and housekeeping

### PR DESCRIPTION
**Pull request by Zinfidel**
Also do a little housekeeping on the ffmpeg build.

### CODE REVIEW

**Comment by vadosnaprimer** [comment]
Since nobody types in this part of the link anymore, it feels like we can just go with `TASVideos.org` (in logos too).

**Comment by Zinfidel** [comment]
Either seems fine to me. I guess a decision on this PR could just be delayed until a consensus in https://tasvideos.org/Forum/Topics/23011 is reached? I made this little PR shortly before I found out that there were opinions on it at all.

**Comment by Zinfidel** [comment]
I also removed Opus support as it just occurred to me that we don't need it anymore, either.

- Moved YouTube FPS fix _after_ halving the framerate just in case this interaction happens some day.
- Various 's's added to links

@vadosnaprimer I noticed at the end of the file, the video was converted to YV24 color space, then immediately converted to YV12 color space. This seems to me like an error, so I removed the YV24 conversion. Also, the conversion to YV12 (lossy) was using point sizing instead of lanczos, which seems like a copy-paste error. I changed this as well. Let me know if this was actually intentional.

**Comment by vadosnaprimer** [comment]
How we do subsampling conversion depends on what looks better. It was done in 2 steps since forever ago, we would need Aktan to tell us why. And whether it's point or lanczos will need to be tested on various AR factors, like A2600 and PSX's 512px mode.

**Comment by Zinfidel** [comment]
On the topic of doing subsampling in two steps, I took a walk down the history and here's what the relevant section looked like:
```
#	YV24 conversion doesn't reduce chroma, so "point" is fine
ConvertToYV24(chromaresample="point", matrix=(hd \
	? "Rec709" \
	: (pass == 0 \
		? "Rec601" \
		: "PC.601")))

# pass == 1 ? assrender("subtitles.ass") : 0

#	Remove duplicate frames for primary
pass == 1 ? ExactDedup(firstpass=true, dupinfo="./temp/dup.txt",times="./temp/times.txt") : 0
pass == 2 ? ExactDedup(firstpass=false,dupinfo="./temp/dup.txt"                         ) : 0

#	YV12 reduces chroma, so we use "lanczos" even for HD
#	http://tasvideos.org/forum/viewtopic.php?t=19426
i444 ? last : ConvertToYV12(chromaresample="lanczos", matrix=(hd \
	? "Rec709" \
	: (pass == 0 \
		? "Rec601" \
		: "PC.601")))
```
My assumption when I looked at this is that YV color space was required for assrender/deduplication, so we did YV24 first to avoid loss before doing that, then went to YV12 as a final step. I could be quite wrong about that being the case though. I'll ping Aktan to get their opinion.

**Comment by vadosnaprimer** [comment]
Further back
https://tasvideos.org/EncodingGuide/Legacy/PreEncoding
https://tasvideos.org/EncodingGuide/Legacy/HybridEncodeScript

**Comment by Zinfidel** [comment]
I'll note that the [forum link](http://tasvideos.org/forum/viewtopic.php?t=19426) that is right above the affected code talks about this and I should have really read through it first. After having done that though, I still have doubts/suspicions. At least theoretically, I can't see a reason why converting pixels directly to YUV color planes before then subsampling the UV planes using the same matrix should make a difference. I guess it depends heavily on how the color conversion algos in AviSynth actually work.

My assumption about how the algorithms works is that they first perform the transfer function on pixels, _then_ resize. If it's the other way around though (why god) then I can see how doing yv24 first would make a difference.

**Comment by despoa** [comment]
I think the RGB -> YV12 conversion is done with a conversion to YV24 as an intermediate step going by [this page](http://avisynth.nl/index.php/Convert).

And with tests with TiKevin's rgbscaler, chroma resampling with filters other than Point introduces chroma artifacts for pixel art. I suggest chroma resampling with Point for when we HD resize by point and with Lanczos for when we HD resize by Lanczos.

And if you're gonna do some housekeeping, I suggest removing the Famtasia and PSXjin functions under LEGACY STUFF. The Famtasia function is rendered unnecessary by FFmpeg's own bit depth conversion (I'm sure YouTube can handle 8-bit FLAC audio. If not, FFmpeg has `-sample_fmt`. Lossy formats like AAC don't care about the bit depth.) and the PSXjin function doesn't work.

**Comment by Zinfidel** [comment]
I tested some colorspace stuff here: https://tasvideos.org/Forum/Topics/19426?CurrentPage=3&Highlight=511622#511622

If my tests aren't bunk, they indicate that we can drop the conversion into YV24 prior to YV12. @Aktanusa recalls that the conversion may have originally been done due to a bug in the YV12 conversion function, but the function appears to work correctly now.

> And with tests with TiKevin's rgbscaler, chroma resampling with filters other than Point introduces chroma artifacts for pixel art. I suggest chroma resampling with Point for when we HD resize by point and with Lanczos for when we HD resize by Lanczos.

I'm willing to believe this at face value honestly, but perhaps there are some images you (@despoa) or @TiKevin83 could share? We could easily accomplish this by doing something like `ConvertToYV12(chromaresample=resizer ...)`

**Comment by Zinfidel** [comment]
> And if you're gonna do some housekeeping, I suggest removing the Famtasia and PSXjin functions under LEGACY STUFF. The Famtasia function is rendered unnecessary by FFmpeg's own bit depth conversion (I'm sure YouTube can handle 8-bit FLAC audio. If not, FFmpeg has -sample_fmt. Lossy formats like AAC don't care about the bit depth.) and the PSXjin function doesn't work.

I agree with removing the Famtasia stuff as long as we confirm ffmpeg doesn't need to be recompiled to do the conversion. If it does, then honestly either way is fine IMO. As for PSXJin, unless I'm missing something, all it's doing is showing you that you need to mux the audio? What doesn't work?

**Comment by despoa** [comment]
> I'm willing to believe this at face value honestly, but perhaps there are some images you (@despoa) or @TiKevin83 could share? We could easily accomplish this by doing something like `ConvertToYV12(chromaresample=resizer ...)`

I discussed this with TiKevin when he couldn't get FFmpeg's own chroma subsampling to produce good results for him. It turns out that FFmpeg's default filter for chroma is bicubic. You get better and sharp results if neighbor/point is used. More details can be found in this link.
https://stackoverflow.com/questions/64692051/why-does-ffmpeg-yuv420p-conversion-affect-pixels-beyond-2x2-blocks

> I agree with removing the Famtasia stuff as long as we confirm ffmpeg doesn't need to be recompiled to do the conversion. If it does, then honestly either way is fine IMO. As for PSXJin, unless I'm missing something, all it's doing is showing you that you need to mux the audio? What doesn't work?

FFmpeg doesn't have to be recompiled. The build parameter `--enable-decoder=pcm*` makes it so that any PCM format listed [here](https://trac.ffmpeg.org/wiki/audio%20types) can be decoded. As for the PSXjin function, it was something feos copypasted from somewhere else before he implemented the multisegment function. I made my own version that works with the multisegment function, but it's up to feos if he wants it in main package.

**Comment by vadosnaprimer** [comment]
> I made my own version that works with the multisegment function, but it's up to feos if he wants it in main package.

Where can I see it?

**Comment by Zinfidel** [comment]
> FFmpeg doesn't have to be recompiled. The build parameter --enable-decoder=pcm* makes it so that any PCM format listed here can be decoded.

You should have seen the list before I found out that you could use wildcards in that file! But my concern was specifically with this:
> FFmpeg's own bit depth conversion

I added the `aresample` filter to the list after discovering that the codecs themselves would not do this on their own. So here I am wondering if the `flac` encoder can handle any PCM format or if it might need the assistance of another filter.

**Comment by despoa** [comment]
> > I made my own version that works with the multisegment function, but it's up to feos if he wants it in main package.
> 
> Where can I see it?

I'll make a pull request to show you.

> I added the `aresample` filter to the list after discovering that the codecs themselves would not do this on their own. So here I am wondering if the `flac` encoder can handle any PCM format or if it might need the assistance of another filter.

From my brief tests with the full package, it looks like it can without any filters. Give it unsigned 8-bit PCM and it outputs 16-bit FLAC. Give it 32-bit floating point PCM and it outputs 24-bit FLAC. Now I'm not sure about the stripped down package we have but looking through the documentation, I don't think we need any additional filters.

**Comment by TiKevin83** [comment]
For reference this is what the error looks like coming out of FFMPEG for very small pixel art when trying to do 2x nearest neighbor scale + 420 to preserve full chroma but not having the accurate_rnd setting or full_chroma_int going.
BicubicChromaError

**Comment by Zinfidel** [comment]
I added a resampling to 48Khz in the ffmpeg command for the SD encode, then experimentally determined a priming offset for that value (5060 samples) that got the audio in line with the flac audio. I tried this command against several input frequencies and they all lined up. Obviously outside testing is welcome to confirm this though.

**Comment by vadosnaprimer** [comment]
Thanks!

**Comment by vadosnaprimer** [comment]
UGH wrong button :/

**Pull request merged**
